::: definition
[]{#def-dsep label="def-dsep"} [@pearl_2009 p.16] A path $p$ is said to be ***d*-separated** (or **blocked**) by a set of nodes $Z$ if and only if
:::

::: theorem
[]{#thm-prob-dsep label="thm-prob_dsep"} [@pearl_2009 p.18] Consider three disjoint subsets of variables $X, Y, Z$, represented by nodes of a given DAG $G$.
:::

::: example
[]{#exm-numerical-coincidence label="exm-numerical_coincidence"} Consider the simplest two-variable DAG, $X \rightarrow Y$, and denote $Z = \emptyset$. Suppose $X$ is a standard gaussian distribution with mean 0, and
:::

::: corollary
[]{#cor-non-adj-d-sep label="cor-non_adj_d_sep"} Given a DAG $G$, if two nodes $X$ and $Y$ are non-adjacent, i.e. there is no direct causal link between them, then there exists a set $Z$ that $d$-separates $X$ from $Y.$ This means that an absence of arrows always implies a conditional independency in a compatible probability distribution. This is sometimes called the **pairwise Markov property** and is easily deduced from the Markov compatibility between $G$ and $\mathbb{P}$[^12].
:::

::: {#def-markov-compatibility}

## Markov compatibility

[@pearl_2009 p.16] If a probability function $\mathbb{P}$ admits a factorization 
$$
\mathbb{P}(X_1, \dots, X_k) = \mathbb{P}(X_1)\prod_{j=2}^k \mathbb{P}(X_j | PA_{X_j}),
$$
 relative to the sets of (Markovian) parents $PA_{X_j}$ given by a DAG $G,$ we say that $G$ **represents** $\mathbb{P},$ that $G$ and $\mathbb{P}$ are **compatible**, that $\mathbb{P}$ is **Markov relative** to $G$, or that $\mathbb{P}$ is **faithful** to $G$[^7].
 
:::

::: proof
*Proof.* A full proof can be found in [@pearl_2009 p.80]. The gist of it is that, when $Z$ blocks all backdoor paths, $\mathbb{P}(Y=y|do(W=w),Z=z) = \mathbb{P}(Y=y|W=w, Z=z).$ Thus, when looking at a stratum of the data where $Z = z,$ the causal effect is not confounded and can be estimated directly from the data. Then, an average of all the stratified causal effects weighted by the probability of the strata, that is $\mathbb{P}(Z=z),$ yields the overall causal effect. ◻
:::

::: definition
[@pearl_2009 p.79] A set of variables $Z$ satisfies the **backdoor criterion** relative to an (ordered) pair of variables $(W, Y)$ in a DAG $G$ if:

1.  no node in $Z$ is a descendant of $W$;

2.  $Z$ blocks every path between $W$ and $Y$ that contains an arrow into $W.$

A set $Z$ that satisfies the backdoor criterion is sometimes called a **sufficient set** for control of confounding [@greenland_pearl_robins_1999].
:::
