---
title: "Test features of Quarto"
author: "Bastien Chassagnol"
date: last-modified	
number-sections: true
toc: true
toc-depth: 4
link-citations: true
highlight-style: github
execute:
  message: false
  warning: false
  error: false
  eval: true
  echo: true
# Table options
tbl-cap-location: bottom
format: 
  html:
    embed-resources: true
    toc-location: left
    toc-expand: 3
    theme: cosmo
    sidebar: true
    lightbox: true
    comments: 
      hypothesis: true
  pdf:
    keep-tex: true
---

See @nte-classification-ccc for a general overviw of tools classification.

::: {#nte-classification-ccc .callout-note title="Main Tools classification"}

- **Data-Driven Approaches** rely on *high-throughput* experimental data (e.g., single-cell RNA-seq, spatial transcriptomics, proteomics) to infer cell-cell interactions using network inference algorithms (e.g., correlation-based, graph learning, deep learning). While their `adhoc` approach enables them to identify novel or context-specific interactions, they are more sensitive to noise and require larger datasets[^spatial-ccc-review-1].

- **Knowledge-Based Approaches** use curated biological databases (e.g., ligand-receptor pairs, signalling pathways) to construct interaction networks, based on **prior knowledge**. While they provide straightforward, mechanistic and biologically meaningful explanations, and are robust against noisy data, they are limited by the accuracy of existing knowledge bases (and so, on the quality of the manual/expert/literature curation), and may miss novel interactions that are not yet characterized in the literature.

- Finally, **hybrid approaches** integrate data-driven insights with knowledge-based constraints, making the best of both worlds. They usually perform best at inferring **context-dependent interactions** with limited number of samples, and are used in Bayesian frameworks, or rule-based AI systems.

**For their versatility and robustness, hybrid approaches are increasingly favored in network-centric approaches**.

:::

